// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  TEMPERATURE_REQUEST
  TEMPERATURE_RECEIVE
  TEMPERATURE_FAILURE

  UPDATE_INPUT
  CLEAR_INPUT

  REQUEST_STOCK_LOOKUP
  RECEIVE_LOOKUP_SUCCESS
  RECEIVE_LOOKUP_FAILURE

  REQUEST_STOCK_QUOTE
  RECEIVE_QUOTE_SUCCESS
  RECEIVE_QUOTE_FAILURE
`)
